import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	map,
	rules,
}: {
	children: React.ReactNode;
	map: React.ReactNode;
	rules: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				{/* <header>Menu</header> */}
				{/* {map}
				{rules} */}
				{children}
			</body>
		</html>
	);
}
